### ISSUE TITLE
Multiple scenes

### ISSUE THREAD

**Issue by OutdoorIRL** [tormyvancool/OBS-STUDIO_Countdown#1]
I am unable to set this up for multiple scenes as a new timer. I need 3 scenes with 3 different timers.

**Comment by tormyvancool** [comment]
It was not meant for this, so it's not an issue.
it's meant to switch to one scene that you chose, for when the counter reaches 0.
What you can do is to replicate the same script changing the filename (name_1.lua, nama_2.lua etc) and employ them when you need.

I close this issue because **it's not an issue**. Just a **different use case**
