### ISSUE TITLE
Bloated repo

### ISSUE THREAD

**Issue by LiGoldragon** [tormyvancool/OBS-STUDIO_Countdown#5]
100 MBytes? Cmon, this is just a lua script! Not the linux kernel. You should rebase.

**Comment by tormyvancool** [comment]
> 100 MBytes? Cmon, this is just a lua script! Not the linux kernel. You should rebase.

what a heck are you telling about my script? 100MB? In which fantasy?

**Comment by LiGoldragon** [comment]
```
ghq get https://github.com/tormyvancool/OBS-STUDIO_Countdown
     clone https://github.com/tormyvancool/OBS-STUDIO_Countdown -> /git/github.com/tormyvancool/OBS-STUDIO_Countdown
       git clone --recursive https://github.com/tormyvancool/OBS-STUDIO_Countdown /git/github.com/tormyvancool/OBS-STUDIO_Countdown
Cloning into '/git/github.com/tormyvancool/OBS-STUDIO_Countdown'...
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 141 (delta 18), reused 10 (delta 10), pack-reused 114
Receiving objects: 100% (141/141), 108.18 MiB | 3.73 MiB/s, done.
Resolving deltas: 100% (66/66), done.
```

**Comment by LiGoldragon** [comment]
Now you can apologize

**Comment by tormyvancool** [comment]
> ```
> ghq get https://github.com/tormyvancool/OBS-STUDIO_Countdown
>      clone https://github.com/tormyvancool/OBS-STUDIO_Countdown -> /git/github.com/tormyvancool/OBS-STUDIO_Countdown
>        git clone --recursive https://github.com/tormyvancool/OBS-STUDIO_Countdown /git/github.com/tormyvancool/OBS-STUDIO_Countdown
> Cloning into '/git/github.com/tormyvancool/OBS-STUDIO_Countdown'...
> remote: Enumerating objects: 141, done.
> remote: Counting objects: 100% (27/27), done.
> remote: Compressing objects: 100% (17/17), done.
> remote: Total 141 (delta 18), reused 10 (delta 10), pack-reused 114
> Receiving objects: 100% (141/141), 108.18 MiB | 3.73 MiB/s, done.
> Resolving deltas: 100% (66/66), done.
> ```

I think you have some issue because ti's few kB stuff.
there is one ANIMATED GIF inside that it takes some MB that's what you see in to the main page. That's it. The script is 9kB.
It's not bloated.

There is not any issue. the user has not knowledge about what' it's downloaded and why and the size of each file nro how the main download of GitHub works.

Here below the screenshot of the downloaded file from GitHub. I downloaded to verify what the user stated.
And it is resulted not corresponding to the reality.

![image](https://github.com/tormyvancool/OBS-STUDIO_Countdown/assets/32305535/ff5fd7c0-7b32-43b4-828f-3a002f790473)

The downloaded ZIp is only 25M this is due the 2 animated GIFs are included. If the user doesn't want the GIF just downloads the single file.

Not any issues are detected with this repository.

![image](https://github.com/tormyvancool/OBS-STUDIO_Countdown/assets/32305535/12b81076-9c34-498e-abbb-6d8da6c89ef5)
